/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mindovercnc_linuxcnc_HalHandler */

#ifndef _Included_com_mindovercnc_linuxcnc_HalHandler
#define _Included_com_mindovercnc_linuxcnc_HalHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mindovercnc_linuxcnc_HalHandler
 * Method:    createComponent
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mindovercnc_linuxcnc_HalHandler_createComponent
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mindovercnc_linuxcnc_HalHandler
 * Method:    addPin
 * Signature: (Lcom/mindovercnc/linuxcnc/HalHandler/Pin;I)V
 */
JNIEXPORT void JNICALL Java_com_mindovercnc_linuxcnc_HalHandler_addPin
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_mindovercnc_linuxcnc_HalHandler
 * Method:    getPin
 * Signature: (Ljava/lang/String;I)Lcom/mindovercnc/linuxcnc/HalHandler/Pin;
 */
JNIEXPORT jobject JNICALL Java_com_mindovercnc_linuxcnc_HalHandler_getPin
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mindovercnc_linuxcnc_HalHandler
 * Method:    setReady
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mindovercnc_linuxcnc_HalHandler_setReady
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
